version: "0.1"
pricing:
  pricing_type: "spot"    # Möglich: "on_demand" oder "spot"
  service_code: "AmazonEC2"
  region: "us-east-1"          # Region im Format, z.B. "us-east-1"
  filters:
    instance_type: "t2.micro"
    operating_system: "Linux"
